### ISSUE TITLE
Linting code string

### ISSUE THREAD

**Issue by Semigradsky** [rossPatton/stylint#160] opened 2015-07-23 08:41 UTC
Hi! Is there any way linting code string? Something like this:
```js
const code = '.className padding 0';

const stylint = require('stylint')({
    brackets: 'always',
    namingConvention: 'BEM',
    semicolons: 'always'
}).create();

const errors = stylint.lint(code);
```
It would be great!

---
Linter like CSSLint, ESLint, JSHint allow it.

**Comment by rossPatton** [comment] 2015-07-23 17:19
It doesn't currently exist but it's something that will probably be added soon.

See: https://github.com/rossPatton/stylint/issues/146

**Comment by Semigradsky** [comment] 2015-07-23 19:12
Nice!

**Comment by rossPatton** [comment] 2015-09-20 07:22
gonna close this since it's a dupe of #146

**Closed by rossPatton** 2015-09-20 07:22 UTC
Labels: enhancement
